# Generated by Django 3.0.3 on 2020-02-11 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('year_born', models.CharField(max_length=100)),
                ('year_died', models.CharField(max_length=100)),
                ('bio_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Creation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='no creation title', max_length=100)),
                ('year_completed', models.CharField(default='no year_completed', max_length=100)),
                ('medium', models.CharField(default='no medium', max_length=100)),
                ('image', models.TextField(null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creations', to='gallery.Creator')),
            ],
        ),
    ]
